apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws01-test-deployment
  labels:
    app: ws01-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws01-test
  template:
    metadata:
      labels:
        app: ws01-test
    spec:
      containers:
      - name: ws01-test
        image: na50r/ws01-test:v1.0
      imagePullSecrets:
      - name: regcred
