@Library('shared-library') _
pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                helloWorldV1(name:'Name', dayOfWeek:'Day')
            }
        }
        stage('Run') {
            steps {
                dir('Workspace01') {
                    sh('cd kubernetes')
                    sh('cd jobs')
                    k8sDeployLocal('Job5')
                }
            }
        }
    }
}
