@Library('shared-library') _
import constants.Env
import functions.K8s

pipeline {
    agent any
    stages {
        stage('Should Job Start?') {
            when {
                anyOf {
                    environment name: 'global_trigger', value: 'false'
                    environment name: 'service', value: 'cockpit'
                    environment name: 'service', value: 'client-gateway'
                }
            }
            steps {
                script {
                    currentBuild.result = 'ABORTED'
                    error('Exiting early with success')
                }
            }
        }

        stage('Print Env') {
            when {
                environment name: 'enum_test', value: Env.ALPHA.toString()
            }
            steps {
                println('Works')
                script {
                    K8s.sayHello()
                }
                sh('env')
            }
        }

        stage('Send Msg') {
            when {
                environment name: 'send_google', value: 'true'
            }
            steps {
                sendGoogleMsgV2(env.webhook_url, 'hi from groovy/http/restClient')
                script {
                    googleBot.sendMsgV2(env.webhook_url, 'hi from groovy/http/restClient')
                }
            }
        }

        stage('Hello') {
            steps {
                helloWorldV1(name: 'Name', dayOfWeek: 'Day')
            }
        }
        stage('Run') {
            steps {
                k8sDeleteJob('ws01-test-job')
                dir('Workspace01/kubernetes/jobs') {
                    k8sDeployLocal('Job5')
                    sleep(5)
                }
                k8sStreamLogs('ws01-test-job')
                k8sDeleteJob('ws01-test-job')
            }
        }

        stage('Run 2') {
            steps {
                script {
                    k8s.deleteJob('ws01-test-job')
                    dir('Workspace01/kubernetes/jobs') {
                        k8s.deployLocal('Job5')
                        sleep(5)
                    }
                    k8s.streamLogs('ws01-test-job')
                    k8s.deleteJob('ws01-test-job')
                }
            }
        }
    }
}
